finance_all/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("finances.urls")),
        path("users/", include("users.urls")),
        path("orders/", include("orders.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

finances/urls.py
from django.urls import include, path

from . import ajax_datatable
from .views import ajax_create_finance, ajax_delete_finance, ajax_diff_budget, index

app_name = "finance"

urlpatterns = [
    path("home/", index, name="index"),
    path(
        "ajax_datatable/permissions/",
        ajax_datatable.PermissionAjaxDatatableView.as_view(),
        name="ajax_datatable_permissions",
    ),
    path("append_finance/", ajax_create_finance, name="append_finance"),
    path(
        "ajax_delete_finance/<int:id>", ajax_delete_finance, name="ajax_delete_finance"
    ),
    path("ajax_diff_budget/", ajax_diff_budget, name="ajax_diff_budget"),
]

orders/urls.py
from django.urls import path

from . import ajax_datatable
from .ajax import (
    ajax_create_order,
    ajax_create_wish,
    ajax_get_order,
    ajax_get_wishlist,
    ajax_update_order,
    ajax_update_wish,
)
from .views import (
    ajax_create_order_view,
    ajax_delete_order,
    table_order,
    table_wishlist,
)

app_name = "orders"


urlpatterns = [
    path(
        "ajax_datatable/permissions/",
        ajax_datatable.OrdersDatatableView.as_view(),
        name="ajax_datatable_permissions",
    ),
    path(
        "ajax_datatable/wishlist/",
        ajax_datatable.WishlistDatatableView.as_view(),
        name="ajax_datatable_wishlist",
    ),
    path(
        "table/",
        table_order,
        name="index",
    ),
    path(
        "table_wish/",
        table_wishlist,
        name="table_wishlist",
    ),
    path("create_order/", ajax_create_order_view, name="create_order"),
    path("ajax_delete_order/<int:id>",
         ajax_delete_order, name="ajax_delete_order"),
    path("ajax_order/", ajax_get_order, name="ajax_order"),
    path("ajax_wishlist/", ajax_get_wishlist, name="ajax_wishlist"),
    path("ajax_update_order/<int:id>",
         ajax_update_order, name="ajax_update_order"),
    path("ajax_update_wish/<int:id>", ajax_update_wish, name="ajax_update_wish"),
    path("ajax_create_order/", ajax_create_order, name="ajax_create_order"),
    path("ajax_create_wish/", ajax_create_wish, name="ajax_create_wish"),
]

users/urls.py
from django.urls import path

from .views import auth, profile, register, sign, sign_out

app_name = "users"

urlpatterns = [
    path("sign/", sign, name="sign"),
    path("login/", auth, name="login"),
    path("registration/", register, name="register"),
    path("sign-out/", sign_out, name="sign_out"),
    path("profile/", profile, name="profile"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- BOOTSTRAP -->

    <link href="{% static 'style.css' %}" rel="stylesheet">

    {% block style %}
    {% endblock %}

</head>
<body>
    <header class="p-3 mb-3 border-bottom">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="#" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
              <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a href="{% url 'finance:index' %}" class="nav-link px-2 link-secondary">Finance</a></li>
              <li><a href="{% url 'orders:index' %}" class="nav-link px-2 link-dark">Orders</a></li>
              <li><a href="{% url 'orders:table_wishlist' %}" class="nav-link px-2 link-dark">Wish list</a></li>
              <li><a href="#" class="nav-link px-2 link-dark">Products</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
              <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
            </form>

            <div class="dropdown text-end">
              <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{% block img %}{% endblock %}" alt="mdo" width="32" height="32" class="rounded-circle">
              </a>
              <ul class="dropdown-menu text-small" style="">
                <li><span class="dropdown-item-text">{{ user.get_full_name }}</span></li>
                <li><a class="dropdown-item" href="#">Settings</a></li>
                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Sign out</a></li>
              </ul>
            </div>
          </div>
        </div>
    </header>


    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>


    <div class="container">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top footer">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="mb-3 mb-md-0 text-muted">© 2022 Company, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
        </ul>
      </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock script %}
</body>
</html>