finance_all/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("finances.urls")),
        path("users/", include("users.urls")),
        path("orders/", include("orders.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

finances/urls.py
from django.urls import include, path

from . import ajax_datatable
from .views import ajax_create_finance, ajax_delete_finance, ajax_diff_budget, index

app_name = "finance"

urlpatterns = [
    path("home/", index, name="index"),
    path(
        "ajax_datatable/permissions/",
        ajax_datatable.PermissionAjaxDatatableView.as_view(),
        name="ajax_datatable_permissions",
    ),
    path("append_finance/", ajax_create_finance, name="append_finance"),
    path(
        "ajax_delete_finance/<int:id>", ajax_delete_finance, name="ajax_delete_finance"
    ),
    path("ajax_diff_budget/", ajax_diff_budget, name="ajax_diff_budget"),
]

users/urls.py
from django.urls import path

from .views import auth, profile, register, sign, sign_out

app_name = "users"

urlpatterns = [
    path("sign/", sign, name="sign"),
    path("login/", auth, name="login"),
    path("registration/", register, name="register"),
    path("sign-out/", sign_out, name="sign_out"),
    path("profile/", profile, name="profile"),
]

finances/models.py
from django.db import models


class Wallet(models.Model):
    class Currency(models.TextChoices):
        RU = "1", "Рубль"
        USD = "2", "Доллар"
        EUR = "3", "Евро"

    name = models.CharField(max_length=100)
    finance = models.ManyToManyField("Finance", blank=True)
    currency = models.CharField(
        max_length=2, choices=Currency.choices, default=Currency.RU
    )
    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Кошелек"
        verbose_name_plural = "Кошельки"

    def __str__(self):
        return self.name


class Finance(models.Model):
    class Currency(models.TextChoices):
        RU = "1", "Рубль"
        USD = "2", "Доллар"
        EUR = "3", "Евро"

    class TypeInOut(models.TextChoices):
        IN = "1", "Зачисление"
        OUT = "2", "Трата"

    name = models.CharField(max_length=500)

    budget = models.FloatField()

    type = models.ForeignKey(
        "TypeFinance", on_delete=models.RESTRICT, blank=True, null=True
    )

    type_inout = models.CharField(
        max_length=2, choices=TypeInOut.choices, default=TypeInOut.IN
    )

    currency = models.CharField(
        max_length=2, choices=Currency.choices, default=Currency.RU
    )

    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Финансы"
        verbose_name_plural = "Финансы"

    def __str__(self):
        return f"{self.budget} {self.currency}"


class TypeFinance(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

finances/forms.py
from django import forms

from .models import Finance


class FinanceForm(forms.ModelForm):
    class Meta:
        model = Finance
        fields = ["name", "budget", "currency", "type"]

finances/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django_ajax.decorators import ajax

from finances.models import Finance, TypeFinance, Wallet
from orders.funcs.get_currency import get_currency
from users.models import CustomUser

from .forms import FinanceForm


def is_ajax(request):
    return request.headers.get("x-requested-with") == "XMLHttpRequest"


@login_required(login_url="/users/sign/")
def index(request):
    photo = CustomUser.objects.get(user=request.user)
    form = FinanceForm()
    return render(
        request,
        "finances/index.html",
        {"url_photo": photo.avatar.url, "form": form},
    )


@ajax
def ajax_create_finance(request):
    if request.method == "POST" and is_ajax(request):
        form = FinanceForm(request.POST)
        finance = form.save(commit=False)
        if finance.budget < 0:
            finance.type_inout = 2
        finance.save()
        wallet = Wallet.objects.filter(customuser__user=request.user)[0]
        wallet.finance.add(finance)
        return JsonResponse({"state": "OK"})


@ajax
def ajax_delete_finance(request, id):
    finance = Finance.objects.get(id=id)
    finance.delete()


@ajax
def ajax_diff_budget(request):

    budget_curr = float(request.POST.get("diff_budget"))

    finances = Finance.objects.filter(wallet__customuser__user=request.user)
    user = CustomUser.objects.get(user=request.user)

    currency = get_currency()
    total_money = 0

    for finance in finances:
        if finance.currency == "2":
            total_money += finance.budget * float(currency["USD"]["Value"])
        elif finance.currency == "3":
            total_money += finance.budget * float(currency["EUR"]["Value"])
        else:
            total_money += finance.budget

    if budget_curr > total_money:
        diff = budget_curr - total_money
        type_ = TypeFinance.objects.get(name="Расхождение")
        finance = Finance(
            name="Расхождение +", budget=diff, type=type_, type_inout="1", currency="1"
        )
        finance.save()
        user.wallet.finance.add(finance)

    elif budget_curr < total_money:
        diff = total_money - budget_curr
        type_ = TypeFinance.objects.get(name="Расхождение")
        finance = Finance(
            name="Расхождение -", budget=diff, type=type_, type_inout="2", currency="1"
        )
        finance.save()
        user.wallet.finance.add(finance)

templates/finances/index.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
    <link href="{% static 'ajax_datatable/css/style.css' %}" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="{% static 'finance/table.css' %}" rel="stylesheet" />
{% endblock %}

{% block img %}
    {{ url_photo }}
{% endblock %}

{% block content %}

    <div class="table-responsive _table">
        <table id="datatable" class="table table-bordered table-hover table-striped">
        </table>
    </div>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#FinanceModal">Add finance</button>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#DiffFinance">Difference budget</button>
    {% csrf_token %}
</div>

    <div class="modal fade" id="FinanceModal" tabindex="-1" aria-labelledby="FinanceModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">New finances</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form class="contactFormFinance">
              <div class="mb-3">
                <label for="recipient-name" class="col-form-label">Name:</label><br>
                {{ form.name }}
              </div>
              <div class="mb-3">
                <label for="recipient-name" class="col-form-label">Budget:</label><br>
                {{ form.budget }}
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Currency:</label><br>
                {{ form.currency }}
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Type:</label><br>
                {{ form.type }}
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary submit" data-bs-dismiss="modal">Create</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="DiffFinance" tabindex="-1" aria-labelledby="DiffFinanceLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Different budget</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form class="contactFormDiff">
                <input id="id_order_" type="hidden">
                <div class="mb-3">
                    <label for="message-text" class="col-form-label">Current budget:</label><br>
                    <input type="number" id="id_curr_budget" name="diff_budget">
                </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary submit" data-bs-dismiss="modal">Create</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}


{% block script %}
    <script type="text/javascript" src="{% static 'ajax_datatable/js/utils.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

    <script>

        $(document).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#datatable'),
                "{% url 'finance:ajax_datatable_permissions' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: true,
                    scrollX: false,
                }, {
                    // extra_data
                    // ...
                },
            );

        });

        const FinanceModal = document.getElementById('FinanceModal')
        FinanceModal.addEventListener('show.bs.modal', event => {
          const button = event.relatedTarget
          const modalTitle = FinanceModal.querySelector('.modal-title')
          const modalBodyInput = FinanceModal.querySelector('.modal-body input')
          modalTitle.textContent = 'Add new finance info'
        });

        const DiffFinance = document.getElementById('DiffFinance')
        DiffFinance.addEventListener('show.bs.modal', event => {
          const button = event.relatedTarget
          const modalTitle = DiffFinance.querySelector('.modal-title')
          const modalBodyInput = DiffFinance.querySelector('.modal-body input')
          modalTitle.textContent = 'Difference budget'
        });


        $('#FinanceModal').find('.submit').on('click', () => {
            $(".contactFormFinance").submit()
        });

        $(".contactFormFinance").submit(function(e){
            e.preventDefault();
            var crf_token = $('[name="csrfmiddlewaretoken"]').attr('value');
            var serializedData = $(this).serialize();
            $.ajax({
                type: 'POST',
                url :  "{% url 'finance:append_finance' %}",
                headers: {"X-CSRFToken": crf_token},
                data : serializedData,
                success : function(response){
                    $.fn.dataTable.tables({
                        api: true
                    }).draw();
                },
                error : function(response){
                    console.log(response)
                }
            });
        });


        $('#DiffFinance').find('.submit').on('click', () => {
            $(".contactFormDiff").submit()
        });

        $(".contactFormDiff").submit(function(e){
            e.preventDefault();
            var crf_token = $('[name="csrfmiddlewaretoken"]').attr('value');
            var serializedData = $(this).serialize();
            $.ajax({
                type: 'POST',
                url :  "{% url 'finance:ajax_diff_budget' %}",
                headers: {"X-CSRFToken": crf_token},
                data : serializedData,
                success : function(response){
                    $.fn.dataTable.tables({
                        api: true
                    }).draw();
                },
                error : function(response){
                    console.log(response)
                }
            });
        });


        $('#datatable').on('draw.dt', function(event) {
            onTableDraw(event);
        });

        var onTableDraw = function (event) {
            var html_table = $(event.target);
            html_table.find('tr').each(function(index, item) {

                try {
                    var row = $(item);
                    text = row.children('td.type_inout').first().text();
                    budget = row.children('td.budget').first().text();

                    if (text == 'Зачисление') {
                        row.css('background-color', '#7fde77');
                    }
                    else if (text == 'Трата') {
                        row.css('background-color', '#ffa4a4');
                    }
                }
                    catch(err) {
                }

            });
        }

    </script>

{% endblock %}