finance_all/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("finances.urls")),
        path("users/", include("users.urls")),
        path("orders/", include("orders.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

orders/urls.py
from django.urls import path

from . import ajax_datatable
from .ajax import (
    ajax_create_order,
    ajax_create_wish,
    ajax_get_order,
    ajax_get_wishlist,
    ajax_update_order,
    ajax_update_wish,
)
from .views import (
    ajax_create_order_view,
    ajax_delete_order,
    table_order,
    table_wishlist,
)

app_name = "orders"


urlpatterns = [
    path(
        "ajax_datatable/permissions/",
        ajax_datatable.OrdersDatatableView.as_view(),
        name="ajax_datatable_permissions",
    ),
    path(
        "ajax_datatable/wishlist/",
        ajax_datatable.WishlistDatatableView.as_view(),
        name="ajax_datatable_wishlist",
    ),
    path(
        "table/",
        table_order,
        name="index",
    ),
    path(
        "table_wish/",
        table_wishlist,
        name="table_wishlist",
    ),
    path("create_order/", ajax_create_order_view, name="create_order"),
    path("ajax_delete_order/<int:id>",
         ajax_delete_order, name="ajax_delete_order"),
    path("ajax_order/", ajax_get_order, name="ajax_order"),
    path("ajax_wishlist/", ajax_get_wishlist, name="ajax_wishlist"),
    path("ajax_update_order/<int:id>",
         ajax_update_order, name="ajax_update_order"),
    path("ajax_update_wish/<int:id>", ajax_update_wish, name="ajax_update_wish"),
    path("ajax_create_order/", ajax_create_order, name="ajax_create_order"),
    path("ajax_create_wish/", ajax_create_wish, name="ajax_create_wish"),
]

users/urls.py
from django.urls import path

from .views import auth, profile, register, sign, sign_out

app_name = "users"

urlpatterns = [
    path("sign/", sign, name="sign"),
    path("login/", auth, name="login"),
    path("registration/", register, name="register"),
    path("sign-out/", sign_out, name="sign_out"),
    path("profile/", profile, name="profile"),
]

orders/models.py
from django.db import models


class Orders(models.Model):
    class State(models.TextChoices):
        TO_BUY = "1", "К покупке"
        BOUGHT = "2", "Куплено"
        SCHEDULED = "3", "Запланировано"
        SCHEDULED_NOT_INCLUDED = "4", "Запланировано (не учитывать в подборе)"
        ABADONED = "5", "Заброшено"
        THINKED = "6", "Обдумывается"

    class Currency(models.TextChoices):
        RU = "1", "Рубль"
        USD = "2", "Доллар"
        EUR = "3", "Евро"

    state = models.CharField(
        max_length=2, choices=State.choices, default=State.SCHEDULED
    )

    name = models.CharField(max_length=500)

    comment = models.TextField(blank=True, null=True)

    url = models.URLField(blank=True, null=True)

    price = models.FloatField()

    currency = models.CharField(
        max_length=2, choices=Currency.choices, default=Currency.RU
    )

    date_buy = models.DateField(blank=True, null=True)

    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Товары"
        verbose_name_plural = "Товар"

    def __str__(self):
        return f"{self.name} {self.price}"


class Wishlist(models.Model):
    class State(models.TextChoices):
        PLAN = "1", "В планых"
        ABADONED = "2", "Заброшено"
        TO_ORDER = "3", "В закупку"

    class Currency(models.TextChoices):
        RU = "1", "Рубль"
        USD = "2", "Доллар"
        EUR = "3", "Евро"

    state = models.CharField(
        max_length=2, choices=State.choices, default=State.PLAN)

    name = models.CharField(max_length=500)

    comment = models.TextField(blank=True, null=True)

    url = models.URLField(blank=True, null=True)

    price = models.FloatField()

    currency = models.CharField(
        max_length=2, choices=Currency.choices, default=Currency.RU
    )

    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Желаемое"
        verbose_name_plural = "Желаемое"

    def __str__(self):
        return f"{self.name} {self.price}"

orders/forms.py
from django import forms

from .models import Orders, Wishlist


class OrderForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = ["state", "name", "comment",
                  "url", "price", "currency", "date_buy"]


class WishlistForm(forms.ModelForm):
    class Meta:
        model = Wishlist
        fields = ["state", "name", "comment", "url", "price", "currency"]

orders/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django_ajax.decorators import ajax

from finances.models import Finance, TypeFinance
from users.models import CustomUser

from .forms import OrderForm
from .models import Orders


def is_ajax(request):
    return request.headers.get("x-requested-with") == "XMLHttpRequest"


def table_order(request):
    photo = CustomUser.objects.get(user=request.user)
    form = OrderForm()
    return render(
        request,
        "orders/table_order.html",
        {"url_photo": photo.avatar.url, "form": form},
    )


def table_wishlist(request):
    photo = CustomUser.objects.get(user=request.user)
    form = OrderForm()
    return render(
        request,
        "orders/table_wishlist.html",
        {"url_photo": photo.avatar.url, "form": form},
    )


@ajax
def ajax_create_order_view(request):
    if request.method == "POST" and is_ajax(request):
        form = OrderForm(request.POST)
        order = form.save(commit=False)
        order.save()

        user = CustomUser.objects.get(user=request.user)
        user.orders.add(order)
        if order.state == "2":
            waste = TypeFinance.objects.get(name="Покупки")
            finance = Finance(
                name=order.name,
                budget=f"-{order.price}",
                type=waste,
                type_inout="2",
                currency=order.currency,
            )
            finance.save()
            user.wallet.finance.add(finance)
        return JsonResponse({"state": "OK"})


@ajax
def ajax_delete_order(request, id):
    order = Orders.objects.get(id=id)
    order.delete()

templates/orders/table.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
    <link href="{% static 'ajax_datatable/css/style.css' %}" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="{% static 'finance/table.css' %}" rel="stylesheet" />
{% endblock %}

{% block img %}
    {{ url_photo }}
{% endblock %}

{% block content %}

    <div class="table-responsive _table">
        <table id="datatable" class="table table-bordered table-hover table-striped">
        </table>
    </div>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#FinanceModal">Add order</button>

</div>

    <div class="modal fade" id="FinanceModal" tabindex="-1" aria-labelledby="FinanceModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">New finances</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form class="contactForm">
              {% csrf_token %}
              <div class="mb-3">
                <label for="recipient-name" class="col-form-label">State:</label><br>
                {{ form.state }}
              </div>
              <div class="mb-3">
                <label for="recipient-name" class="col-form-label">Name:</label><br>
                {{ form.name }}
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">URL:</label><br>
                {{ form.url }}
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Price:</label><br>
                {{ form.price }}
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Currency:</label><br>
                {{ form.currency }}
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Date buy:</label><br>
                {{ form.date_buy }}
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary submit" data-bs-dismiss="modal">Create</button>
          </div>
        </div>
      </div>
{% endblock %}


{% block script %}
    <script type="text/javascript" src="{% static 'ajax_datatable/js/utils.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

    <script>

        $(document).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#datatable'),
                "{% url 'orders:ajax_datatable_permissions' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: true,
                    scrollX: false,
                }, {
                    // extra_data
                    // ...
                },
            );

        });

        const FinanceModal = document.getElementById('FinanceModal')
        FinanceModal.addEventListener('show.bs.modal', event => {
          const button = event.relatedTarget
          const modalTitle = FinanceModal.querySelector('.modal-title')
          const modalBodyInput = FinanceModal.querySelector('.modal-body input')
          modalTitle.textContent = 'Add new finance info'
        });

        $(".contactForm").submit(function(e){
            e.preventDefault();
            var serializedData = $(this).serialize();
            $.ajax({
                type: 'POST',
                url :  "{% url 'orders:create_order' %}",
                data : serializedData,
                success : function(response){
                    $.fn.dataTable.tables({
                        api: true
                    }).draw();
                },
                error : function(response){
                    console.log(response)
                }
            });
        });

        const button = document.querySelector(".submit");

        button.addEventListener("click", () => {
            $(".contactForm").submit()
        });

        $('#datatable').on('draw.dt', function(event) {
            onTableDraw(event);
        });

        var onTableDraw = function (event) {
            var html_table = $(event.target);
            html_table.find('tr').each(function(index, item) {

                try {
                    var row = $(item);
                    text = row.children('td.state').first().text();
                    console.log(text);

                    url = row.children('td.url').first()

                    url.html(`<a href='${url.text()}'>${row.children('td.name').first().text()}</a>`)

                    if (text == 'Куплено') {
                        row.css('background-color', '#7fde77');
                    }
                    else if (text == 'Заброшено') {
                        row.css('background-color', '#ffa4a4');
                    }
                    else if (text == 'Запланировано') {
                        row.css('background-color', '#ffc3fb');
                    }
                }
                    catch(err) {
                }

            });
        }

    </script>

{% endblock %}

templates/orders/table_order.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
    <link href="{% static 'ajax_datatable/css/style.css' %}" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="{% static 'finance/table.css' %}" rel="stylesheet" />
{% endblock %}

{% block img %}
    {{ url_photo }}
{% endblock %}

{% block content %}

    <div class="table-responsive _table">
        <table id="datatable" class="table table-bordered table-hover table-striped">
        </table>
    </div>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#OrderModal">Add order</button>

</div>

    <div class="modal fade" id="OrderModal" tabindex="-1" aria-labelledby="OrderModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">New Order</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form class="contactForm">
              {% csrf_token %}
              <div class="mb-3">
                <label for="recipient-name" class="col-form-label">State:</label><br>
                {{ form.state }}
              </div>
              <div class="mb-3">
                <label for="recipient-name" class="col-form-label">Name:</label><br>
                {{ form.name }}
              </div>
              <div class="mb-3">
                <label for="recipient-name" class="col-form-label">Comment:</label><br>
                {{ form.comment }}
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">URL:</label><br>
                {{ form.url }}
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Price:</label><br>
                {{ form.price }}
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Currency:</label><br>
                {{ form.currency }}
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Date buy:</label><br>
                {{ form.date_buy }}
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary submit" data-bs-dismiss="modal">Create</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}


{% block script %}
    <script type="text/javascript" src="{% static 'ajax_datatable/js/utils.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

    <script>

        $(document).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#datatable'),
                "{% url 'orders:ajax_datatable_permissions' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: true,
                    full_row_select: true,
                    scrollX: false,
                }, {
                    // extra_data
                    // ...
                },
            );

        });

        const OrderModal = document.getElementById('OrderModal')
        OrderModal.addEventListener('show.bs.modal', event => {
          const button = event.relatedTarget
          const modalTitle = OrderModal.querySelector('.modal-title')
          const modalBodyInput = OrderModal.querySelector('.modal-body input')
          modalTitle.textContent = 'Add new order info'
        });

        $(".contactForm").submit(function(e){
            e.preventDefault();
            var serializedData = $(this).serialize();
            $.ajax({
                type: 'POST',
                url :  "{% url 'orders:create_order' %}",
                data : serializedData,
                success : function(response){
                    $.fn.dataTable.tables({
                        api: true
                    }).draw();
                },
                error : function(response){
                    console.log(response)
                }
            });
        });

        const button = document.querySelector(".submit");

        button.addEventListener("click", () => {
            $(".contactForm").submit()
        });

        $('#datatable').on('draw.dt', function(event) {
            onTableDraw(event);
        });

        var onTableDraw = function (event) {
            var html_table = $(event.target);
            html_table.find('tr').each(function(index, item) {

                try {
                    var row = $(item);
                    text = row.children('td.state').first().text();

                    url = row.children('td.url').first()

                    if (url.text() != '') {
                        url.html(`<a href='${url.text()}'>${row.children('td.name').first().text()}</a>`)
                    } else {
                        url.html('–')
                    }

                    if (text == 'Куплено') {
                        row.css('background-color', '#7fde77');
                    }
                    else if (text == 'Заброшено') {
                        row.css('background-color', '#ffa4a4');
                    }
                    else if (text == 'Запланировано') {
                        row.css('background-color', '#ffc3fb');
                    }
                    else if (text == 'Запланировано (не учитывать в подборе)') {
                        row.css('background-color', '#f3b353');
                    }
                    else if (text == 'Обдумывается') {
                        row.css('background-color', '#53eef3');
                    }
                }
                    catch(err) {
                }

            });
        }

    </script>

{% endblock %}

templates/orders/table_wishlist.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
    <link href="{% static 'ajax_datatable/css/style.css' %}" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="{% static 'finance/table.css' %}" rel="stylesheet" />
{% endblock %}

{% block img %}
    {{ url_photo }}
{% endblock %}

{% block content %}

    <div class="table-responsive _table">
        <table id="datatable" class="table table-bordered table-hover table-striped">
        </table>
    </div>
{% endblock %}


{% block script %}
    <script type="text/javascript" src="{% static 'ajax_datatable/js/utils.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

    <script>

        $(document).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#datatable'),
                "{% url 'orders:ajax_datatable_wishlist' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: true,
                    full_row_select: true,
                    scrollX: false,
                }, {
                    // extra_data
                    // ...
                },
            );

        });

        $('#datatable').on('draw.dt', function(event) {
            onTableDraw(event);
        });

        var onTableDraw = function (event) {
            var html_table = $(event.target);
            html_table.find('tr').each(function(index, item) {

                try {
                    var row = $(item);
                    text = row.children('td.state').first().text();

                    url = row.children('td.url').first()

                    if (text == 'В планых') {
                        row.css('background-color', '#7fde77');
                    }
                    else if (text == 'Заброшено') {
                        row.css('background-color', '#ffa4a4');
                    }
                }
                    catch(err) {
                }

            });
        }

    </script>

{% endblock %}